services: 
  mariadb:
    build: /home/ybellakr/inception/srcs/requirements/mariadb
    image: mariadb:ybellakr
    secrets:
      - db_password
      - db_root_password
    env_file:
      - .env
    container_name: mariadb
    networks:
      - inception
    volumes:
      - mariadb:/var/lib/mysql
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 10s
      retries: 5
      start_period: 5s
      timeout: 5s
    restart: always
  
  wordpress:
    build: /home/ybellakr/inception/srcs/requirements/wordpress
    image: wordpress:ybellakr
    secrets:
      - credentials
      - db_password
      - pass_user2
    env_file:
      - .env
    volumes:
      - wordpress:/var/www/wordpress
    container_name: wordpress
    depends_on:
      mariadb:
         condition: service_healthy
    networks:
      - inception
    restart: always

  nginx:
    build: /home/ybellakr/inception/srcs/requirements/nginx
    image: nginx:ybellakr
    container_name: nginx
    networks:
      - inception
    volumes:
      - wordpress:/var/www/wordpress
    depends_on:
      - wordpress
    restart: always
    ports:
      - 443:443

  static:
    build: /home/ybellakr/inception/srcs/requirements/bonus/static_website
    image: static:ybellakr
    container_name: static
    networks:
      - inception
    ports:
      - 4444:4444

  adminer:
    build: /home/ybellakr/inception/srcs/requirements/bonus/adminer
    image: adminer:ybellakr
    container_name: adminer
    networks:
      - inception
    ports:
      - 8000:8888

networks:
  inception:
    driver: bridge
  
volumes:
  wordpress:
    name: "wordpress"
    driver: local
    driver_opts:
      type: none
      o: bind
      device: /home/ybellakr/data/wordpress 
  mariadb:
    name: "mariadb"
    driver: local
    driver_opts:
      type: none
      o: bind
      device: /home/ybellakr/data/mariadb

secrets:
  db_password:
    file: ../secrets/db_password.txt
  db_root_password:
    file: ../secrets/db_root_password.txt
  credentials:
    file: ../secrets/credentials.txt
  pass_user2:
    file: ../secrets/user_password.txt
