services: 
  mariadb:
    build: /home/inception/Downloads/inception/mariadb
    image: mariadb_image
    container_name: mariadb
    networks:
      - inception
    healthcheck:
      test: ["CMD", "ls"]
      interval: 10s
      retries: 5
      start_period: 5s
      timeout: 5s
  
  wordpress:
    build: /home/inception/Downloads/inception/wordpress
    image: wordpress_image
    volumes:
      - DB:/var/www/wordpress
    container_name: wordpress
    depends_on:
      mariadb :
         condition: service_healthy
    networks:
      - inception
    healthcheck:
      test: ["CMD", "ls"]
      interval: 10s
      retries: 5
      start_period: 5s
      timeout: 5s

  nginx:
    build: /home/inception/Downloads/inception/nginx
    image: nginx_image
    container_name: nginx
    networks:
      - inception
    volumes:
      - DB:/var/www/wordpress
    depends_on:
      wordpress:
        condition: service_healthy
    restart: always
    ports:
      - 443:443

  static:
    build: /home/inception/Downloads/inception/static_website
    image: static_image
    container_name: static
    networks:
      - inception
    ports:
      - 4444:4444

  adminer:
    build: /home/inception/Downloads/inception/adminer
    image: adminer_image
    container_name: adminer
    networks:
      - inception
    ports:
      - 8000:8888

networks:
  inception:
    driver: bridge
  
volumes:
 DB:
  name: "DB"
  driver: local
  driver_opts:
    device: /home/inception/Downloads/inception/wp
    o: bind
    type: none